export const FLASHCARDS = [
  {
    id: "var",
    front: "How do you declare a variable in GDScript?",
    back: "Use var:\nvar health = 100\nvar name: String = \"Hero\"",
    tag: "basics",
  },
  {
    id: "const",
    front: "What's the difference between var and const?",
    back: "const never changes after assignment.\nvar can be reassigned anytime.\n\nconst MAX_HP = 100",
    tag: "basics",
  },
  {
    id: "types",
    front: "Name common GDScript built-in types",
    back: "Scalars: int, float, String, bool\nContainers: Array, Dictionary\nMath: Vector2, Vector3, Color\nAlso: Callable, Signal, PackedScene…",
    tag: "basics",
  },
  {
    id: "typed-var",
    front: "How do you add a static type to a variable?",
    back: "var speed: float = 200.0\nvar enemies: Array[Node] = []\n\nTypes catch bugs earlier in the editor.",
    tag: "basics",
  },
  {
    id: "string-format",
    front: "How do you format strings in GDScript?",
    back: '"HP: %s" % health\n"Hi %s, score %d" % [name, score]\nAlso: str(value) to convert to String.',
    tag: "basics",
  },
  {
    id: "null",
    front: "What is null used for?",
    back: "\"No value yet.\" Check with:\nif node == null:\n    return\n\nor: if not is_instance_valid(node):",
    tag: "basics",
  },
  {
    id: "func",
    front: "How do you define a function?",
    back: "func heal(amount: int) -> void:\n    health += amount\n\nfunc get_hp() -> int:\n    return health",
    tag: "functions",
  },
  {
    id: "default-args",
    front: "Can functions have default arguments?",
    back: "Yes:\nfunc shoot(damage := 10, pierce := false):\n    ...\n\nCall: shoot() or shoot(25, true)",
    tag: "functions",
  },
  {
    id: "return-type",
    front: "How do you declare a return type?",
    back: "func add(a: int, b: int) -> int:\n    return a + b\n\nUse -> void when nothing is returned.",
    tag: "functions",
  },
  {
    id: "ready",
    front: "When does _ready() run?",
    back: "Once, after the node and all its children have entered the scene tree.\nSafe place to grab $Child nodes.",
    tag: "lifecycle",
  },
  {
    id: "enter-tree",
    front: "_enter_tree() vs _ready()?",
    back: "_enter_tree: as soon as the node joins the tree (children may not be ready).\n_ready: children are ready — prefer this for setup.",
    tag: "lifecycle",
  },
  {
    id: "process",
    front: "What is _process(delta)?",
    back: "Called every rendered frame.\ndelta = seconds since last frame.\nUse for non-physics visuals, timers, UI polish.",
    tag: "lifecycle",
  },
  {
    id: "physics",
    front: "When should you use _physics_process?",
    back: "For movement & physics that must stay in sync with the physics step (fixed rate).\nCharacterBody2D movement belongs here.",
    tag: "lifecycle",
  },
  {
    id: "exit-tree",
    front: "When does _exit_tree() run?",
    back: "When the node leaves the scene tree.\nGood for disconnecting signals / cleanup.",
    tag: "lifecycle",
  },
  {
    id: "signal",
    front: "What are signals?",
    back: "Godot's event system.\nA node emits; other nodes connect callbacks.\nLoose coupling without hard references.",
    tag: "signals",
  },
  {
    id: "connect",
    front: "How do you connect a signal in code (Godot 4)?",
    back: "button.pressed.connect(_on_button_pressed)\n\n# with binds:\ntimer.timeout.connect(_on_timeout.bind(id))",
    tag: "signals",
  },
  {
    id: "emit",
    front: "How do you declare and emit a custom signal?",
    back: "signal health_changed(value: int)\n\nfunc damage(d):\n    health -= d\n    health_changed.emit(health)",
    tag: "signals",
  },
  {
    id: "disconnect",
    front: "How do you disconnect a signal?",
    back: "if button.pressed.is_connected(_on_pressed):\n    button.pressed.disconnect(_on_pressed)",
    tag: "signals",
  },
  {
    id: "await-signal",
    front: "How do you await a signal?",
    back: "await animation_player.animation_finished\nawait get_tree().create_timer(1.0).timeout\n\nPauses the function until it fires.",
    tag: "signals",
  },
  {
    id: "node",
    front: "What is a Node?",
    back: "The building block of every Godot scene.\nEverything in the tree inherits from Node\n(Node2D, Control, RigidBody3D, etc.).",
    tag: "godot",
  },
  {
    id: "scene",
    front: "What is a scene (.tscn)?",
    back: "A reusable tree of nodes saved to disk.\nInstantiate with preload(...).instantiate()\nor drag into another scene.",
    tag: "godot",
  },
  {
    id: "export",
    front: "What does @export do?",
    back: "Shows the variable in the Inspector.\n@export var speed := 200.0\n@export_range(0, 100) var armor: int",
    tag: "godot",
  },
  {
    id: "onready",
    front: "What does @onready do?",
    back: "Assigns when the node is ready (children exist):\n@onready var label: Label = $Label\n\nSafer than assigning in the var line for $ paths.",
    tag: "godot",
  },
  {
    id: "getnode",
    front: "How do you get a child node by path?",
    back: "$Path/To/Node\nget_node(\"Path/To/Node\")\nget_node_or_null(\"...\")  # returns null if missing",
    tag: "godot",
  },
  {
    id: "groups",
    front: "What are node groups?",
    back: "Tags for many nodes at once.\nadd_to_group(\"enemies\")\nget_tree().call_group(\"enemies\", \"take_damage\", 10)",
    tag: "godot",
  },
  {
    id: "unique-name",
    front: "What is %UniqueName / unique names?",
    back: "In the editor, mark a node unique → access with %Name from any descendant without the full path.\n@onready var hud = %HUD",
    tag: "godot",
  },
  {
    id: "array",
    front: "How do you create and use an Array?",
    back: "var items = [1, 2, 3]\nitems.append(4)\nitems.size()\nitems.has(2)\nfor i in items: print(i)",
    tag: "data",
  },
  {
    id: "dict",
    front: "How do you create a Dictionary?",
    back: 'var stats = {"hp": 10, "mp": 5}\nstats["hp"] += 1\nstats.get("armor", 0)\nfor key in stats: print(key)',
    tag: "data",
  },
  {
    id: "typed-array",
    front: "How do you make a typed Array?",
    back: "var names: Array[String] = []\nvar foes: Array[Enemy] = []\n\nHelps autocomplete and catches wrong types.",
    tag: "data",
  },
  {
    id: "for",
    front: "How do you loop in GDScript?",
    back: "for item in items:\n    print(item)\nfor i in range(5):\n    print(i)\nfor i in range(0, 10, 2):  # step 2",
    tag: "control",
  },
  {
    id: "while",
    front: "How does a while loop look?",
    back: "var i = 0\nwhile i < 10:\n    i += 1\n\nPrefer for when you know the count.",
    tag: "control",
  },
  {
    id: "if",
    front: "Write a simple if / elif / else",
    back: "if hp <= 0:\n    die()\nelif hp < 20:\n    warn_low()\nelse:\n    ok()",
    tag: "control",
  },
  {
    id: "match",
    front: "What is match?",
    back: "Switch-like branching:\nmatch state:\n    \"idle\": play_idle()\n    \"run\": play_run()\n    _: pass  # default",
    tag: "control",
  },
  {
    id: "ternary",
    front: "Is there a ternary operator?",
    back: "Yes:\nvar label = \"dead\" if hp <= 0 else \"alive\"",
    tag: "control",
  },
  {
    id: "class_name",
    front: "What does class_name do?",
    back: "Registers a global class:\nclass_name Player\nextends CharacterBody2D\n\nOthers can type Player and call Player.new().",
    tag: "classes",
  },
  {
    id: "extends",
    front: "What does extends mean?",
    back: "Your script inherits that type:\nextends Node2D\nextends CharacterBody2D\n\nMust match (or be compatible with) the node you attach to.",
    tag: "classes",
  },
  {
    id: "super",
    front: "How do you call a parent method?",
    back: "func _ready():\n    super()\n    # your setup\n\nOr: super.some_method()",
    tag: "classes",
  },
  {
    id: "inner-class",
    front: "Can you define an inner class?",
    back: "Yes:\nclass Bullet:\n    var speed = 400\n\nvar b = Bullet.new()",
    tag: "classes",
  },
  {
    id: "vector2",
    front: "What is Vector2 used for?",
    back: "2D position, direction, size.\nposition += Vector2.RIGHT * speed * delta\nvar dir = (target - position).normalized()",
    tag: "math",
  },
  {
    id: "delta",
    front: "Why multiply movement by delta?",
    back: "So speed is the same at 30 FPS or 144 FPS.\nposition += velocity * delta\n# velocity in units per second",
    tag: "math",
  },
  {
    id: "lerp",
    front: "What does lerp do?",
    back: "Linear interpolate toward a value:\nrotation = lerp_angle(rotation, target, 0.1)\nposition = position.lerp(goal, 1.0 - exp(-speed * delta))",
    tag: "math",
  },
  {
    id: "clamp",
    front: "How do you clamp a number?",
    back: "health = clamp(health, 0, max_health)\n\nKeeps a value inside a min/max range.",
    tag: "math",
  },
  {
    id: "preload",
    front: "preload vs load?",
    back: "preload(\"res://...\") — at parse time, path must be constant.\nload(\"res://...\") — at runtime, can be dynamic.\nPrefer preload when you know the path.",
    tag: "resources",
  },
  {
    id: "resource",
    front: "What is a Resource?",
    back: "Shareable data object (.tres / built-ins).\nTextures, audio, custom stats:\nclass_name ItemData\nextends Resource",
    tag: "resources",
  },
  {
    id: "instantiate",
    front: "How do you spawn a scene from code?",
    back: "var scene = preload(\"res://enemy.tscn\")\nvar e = scene.instantiate()\nadd_child(e)\ne.global_position = spawn_pos",
    tag: "resources",
  },
  {
    id: "characterbody",
    front: "How does CharacterBody2D move in Godot 4?",
    back: "velocity = input_dir * speed\nmove_and_slide()  # no args\n# reads/writes velocity for you",
    tag: "physics",
  },
  {
    id: "raycast",
    front: "What's a quick way to raycast?",
    back: "Use RayCast2D/3D nodes, or:\nvar space = get_world_2d().direct_space_state\nvar query = PhysicsRayQueryParameters2D.create(from, to)\nvar hit = space.intersect_ray(query)",
    tag: "physics",
  },
  {
    id: "area",
    front: "Area2D body_entered — typical use?",
    back: "Detect overlaps (pickups, hitboxes).\nConnect body_entered / area_entered\nand react when something overlaps.",
    tag: "physics",
  },
  {
    id: "input",
    front: "How do you read player input?",
    back: "Input.is_action_pressed(\"jump\")\nInput.get_vector(\"left\",\"right\",\"up\",\"down\")\n\nDefine actions in Project → Input Map.",
    tag: "input",
  },
  {
    id: "input-event",
    front: "_input vs _unhandled_input?",
    back: "_input: sees events first.\n_unhandled_input: only if nothing else consumed them (good for gameplay).",
    tag: "input",
  },
  {
    id: "tween",
    front: "How do you tween a property?",
    back: "var t = create_tween()\nt.tween_property(self, \"modulate:a\", 0.0, 0.4)\nt.tween_callback(queue_free)",
    tag: "animation",
  },
  {
    id: "animation-player",
    front: "What is AnimationPlayer for?",
    back: "Timeline animations on properties / method tracks / audio.\nplay(\"run\")\nawait animation_finished",
    tag: "animation",
  },
  {
    id: "autoloads",
    front: "What is an Autoload (singleton)?",
    back: "A script/scene always available globally.\nProject Settings → Autoload → e.g. Game\nThen: Game.score += 1 from anywhere.",
    tag: "architecture",
  },
  {
    id: "setget",
    front: "How do property getters/setters work?",
    back: "var hp := 100:\n    set(value):\n        hp = clamp(value, 0, max_hp)\n        hp_changed.emit(hp)",
    tag: "architecture",
  },
  {
    id: "static-func",
    front: "What is a static func?",
    back: "Belongs to the class, not an instance:\nstatic func roll() -> int:\n    return randi_range(1, 6)\n\nCall: Dice.roll()",
    tag: "architecture",
  },
  {
    id: "enum",
    front: "How do you define an enum?",
    back: "enum State { IDLE, RUN, JUMP }\nvar state = State.IDLE\n\nmatch state:\n    State.RUN: ...",
    tag: "basics",
  },
  {
    id: "assert",
    front: "What does assert do?",
    back: "assert(health > 0, \"HP should be positive\")\nCrashes in debug if false — great for catching impossible states early.",
    tag: "basics",
  },
  {
    id: "print-rich",
    front: "Debug printing tips?",
    back: "print(value)\nprint_debug(\"here\")  # includes source line\npush_warning(\"weird\")\npush_error(\"bad\")",
    tag: "basics",
  },
  {
    id: "node3d",
    front: "What is Node3D?",
    back: "Base for 3D spatial nodes — has position, rotation, scale in 3D.\nChildren: MeshInstance3D, Camera3D, CharacterBody3D…",
    tag: "3d",
  },
  {
    id: "vector3",
    front: "How does Vector3 differ from Vector2?",
    back: "Adds Z depth.\nVector3(x, y, z)\nOften Y is up in 3D Godot (depends on setup).",
    tag: "3d",
  },
  {
    id: "charbody3d",
    front: "How do you move a CharacterBody3D?",
    back: "Same idea as 2D:\nvelocity = direction * speed\nmove_and_slide()\nUse Input.get_vector + transform.basis for camera-relative move.",
    tag: "3d",
  },
  {
    id: "camera3d",
    front: "What does Camera3D do?",
    back: "Renders the 3D world from its transform.\nMake it current to view through it.\nPair with SpringArm3D for third-person.",
    tag: "3d",
  },
];

export const CARD_TAGS = [
  "all",
  "basics",
  "functions",
  "lifecycle",
  "signals",
  "godot",
  "data",
  "control",
  "classes",
  "math",
  "resources",
  "physics",
  "input",
  "animation",
  "architecture",
  "3d",
];

export function wrongAnswersFor(card, deck = FLASHCARDS, count = 3) {
  const others = deck.filter((c) => c.id !== card.id);
  const shuffled = [...others].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((c) => c.back);
}

export function cardsByTag(tag) {
  if (!tag || tag === "all") return FLASHCARDS;
  return FLASHCARDS.filter((c) => c.tag === tag);
}
