export const BUG_QUESTIONS = [
  {
    id: "b1",
    prompt: "Which line is wrong?",
    lines: ["extends Node2D", "func _ready()", "    print(\"hello\")"],
    wrongIndex: 1,
    explain: "Function headers need a colon: func _ready():",
  },
  {
    id: "b2",
    prompt: "Spot the type bug",
    lines: ["var health: int = 100", "health = \"full\"", "print(health)"],
    wrongIndex: 1,
    explain: "health is typed as int — you can't assign a String to it.",
  },
  {
    id: "b3",
    prompt: "Which line breaks?",
    lines: ["signal died", "func take_damage():", "    died()"],
    wrongIndex: 2,
    explain: "Emit signals with .emit(): died.emit()",
  },
  {
    id: "b4",
    prompt: "Find the frame-rate trap",
    lines: [
      "func _process(delta):",
      "    position.x += speed",
      "    # speed is pixels per second",
    ],
    wrongIndex: 1,
    explain: "Multiply by delta: position.x += speed * delta",
  },
  {
    id: "b5",
    prompt: "What's invalid here?",
    lines: [
      "@onready var label = $Label",
      "func _init():",
      "    label.text = \"Hi\"",
    ],
    wrongIndex: 2,
    explain: "_init runs before the tree exists — $Label / @onready aren't ready. Use _ready().",
  },
  {
    id: "b6",
    prompt: "Spot the syntax error",
    lines: ["var items = [1, 2, 3]", "for i in items", "    print(i)"],
    wrongIndex: 1,
    explain: "for loops need a colon: for i in items:",
  },
  {
    id: "b7",
    prompt: "Godot 4 movement bug",
    lines: [
      "extends CharacterBody2D",
      "func _physics_process(delta):",
      "    move_and_slide(velocity)",
    ],
    wrongIndex: 2,
    explain: "In Godot 4 call move_and_slide() with no args — set velocity first.",
  },
  {
    id: "b8",
    prompt: "Find the const abuse",
    lines: ["const MAX = 10", "MAX = 20", "print(MAX)"],
    wrongIndex: 1,
    explain: "const cannot be reassigned.",
  },
  {
    id: "b9",
    prompt: "Dictionary access bug",
    lines: ["var d = {\"a\": 1}", "print(d.a)", "print(d[\"a\"])"],
    wrongIndex: 1,
    explain: "Dictionary keys use d[\"a\"], not d.a (that's for object properties).",
  },
  {
    id: "b10",
    prompt: "Spot the error",
    lines: ["func add(a, b)", "    return a + b", ""],
    wrongIndex: 0,
    explain: "Missing colon: func add(a, b):",
  },
  {
    id: "b11",
    prompt: "Which line fails at runtime?",
    lines: [
      "var node = get_node(\"Enemy\")",
      "node.queue_free()",
      "node.position.x = 0",
    ],
    wrongIndex: 2,
    explain: "Don't use a node after queue_free() — it becomes invalid.",
  },
  {
    id: "b12",
    prompt: "Find the bad line",
    lines: [
      "@export var speed = 200",
      "func _process(delta):",
      "    translate(Vector2.RIGHT * speed)",
    ],
    wrongIndex: 2,
    explain: "Missing * delta — motion depends on framerate.",
  },
  {
    id: "b13",
    prompt: "What's incorrect?",
    lines: ["class_name Player", "extends Node2D", "var Player = 1"],
    wrongIndex: 2,
    explain: "Don't shadow class_name with a variable of the same name.",
  },
  {
    id: "b14",
    prompt: "Spot the bug",
    lines: ["if health = 0:", "    die()", "    return"],
    wrongIndex: 0,
    explain: "Comparison is ==. Use if health == 0:",
  },
  {
    id: "b15",
    prompt: "Which line is wrong?",
    lines: [
      "await get_tree().create_timer(1.0)",
      "print(\"done\")",
      "return true",
    ],
    wrongIndex: 0,
    explain: "Await the timeout signal: await get_tree().create_timer(1.0).timeout",
  },
  {
    id: "b16",
    prompt: "Signal connect bug",
    lines: [
      "func _ready():",
      "    $Button.pressed.connect(_on_pressed())",
      "func _on_pressed():",
    ],
    wrongIndex: 1,
    explain: "Pass the Callable, don't call it: .connect(_on_pressed) — no ().",
  },
  {
    id: "b17",
    prompt: "Indentation / block bug",
    lines: [
      "func boom():",
      "print(\"kaboom\")",
      "    queue_free()",
    ],
    wrongIndex: 1,
    explain: "The body of boom() must be indented under the func.",
  },
  {
    id: "b18",
    prompt: "Wrong await usage",
    lines: [
      "func fade():",
      "    create_tween().tween_property(self, \"modulate:a\", 0.0, 0.3)",
      "    queue_free()",
    ],
    wrongIndex: 2,
    explain: "Tween is async — await the tween finished (or tween_callback) before queue_free.",
  },
  {
    id: "b19",
    prompt: "Input Map mistake",
    lines: [
      "func _physics_process(_d):",
      "    if Input.is_key_pressed(\"ui_accept\"):",
      "        jump()",
    ],
    wrongIndex: 1,
    explain: "is_key_pressed expects a Key enum, not an action string. Use Input.is_action_just_pressed(\"ui_accept\").",
  },
  {
    id: "b20",
    prompt: "Range loop bug",
    lines: [
      "for i in range(items.size)",
      "    print(items[i])",
      "",
    ],
    wrongIndex: 0,
    explain: "size is a method: items.size() — and the for needs a colon.",
  },
  {
    id: "b21",
    prompt: "Node path typo effect",
    lines: [
      "@onready var anim = $AnimationPlayer",
      "func _ready():",
      "    $AnmimationPlayer.play(\"run\")",
    ],
    wrongIndex: 2,
    explain: "Misspelled node path — use the @onready anim variable: anim.play(\"run\").",
  },
  {
    id: "b22",
    prompt: "Export hint issue",
    lines: [
      "export var damage = 5",
      "func attack():",
      "    print(damage)",
    ],
    wrongIndex: 0,
    explain: "Godot 4 uses @export, not the old export keyword.",
  },
  {
    id: "b23",
    prompt: "Boolean logic smell",
    lines: [
      "if is_dead == true:",
      "    return",
      "move()",
    ],
    wrongIndex: 0,
    explain: "Write if is_dead: — comparing == true is redundant (not a crash, but the \"wrong\" style line to fix).",
  },
  {
    id: "b24",
    prompt: "PackedScene spawn bug",
    lines: [
      "var enemy = preload(\"res://enemy.tscn\")",
      "add_child(enemy)",
      "enemy.position = Vector2.ZERO",
    ],
    wrongIndex: 1,
    explain: "preload returns a PackedScene — call .instantiate() before add_child.",
  },
];

export const MATCH_PAIRS = [
  { id: "m1", term: "signal", definition: "Event you can emit and connect to" },
  { id: "m2", term: "@export", definition: "Show a variable in the Inspector" },
  { id: "m3", term: "_ready()", definition: "Runs once when the node & children are ready" },
  { id: "m4", term: "extends", definition: "Inherit from a class or node type" },
  { id: "m5", term: "Vector2", definition: "2D position or direction" },
  { id: "m6", term: "delta", definition: "Seconds since the previous frame" },
  { id: "m7", term: "$Node", definition: "Shorthand for get_node(\"Node\")" },
  { id: "m8", term: "queue_free()", definition: "Delete this node safely soon" },
  { id: "m9", term: "preload()", definition: "Load a resource at parse time" },
  { id: "m10", term: "match", definition: "Switch-style branching on a value" },
  { id: "m11", term: "CharacterBody2D", definition: "Body for player/enemy movement" },
  { id: "m12", term: "class_name", definition: "Register a global script class" },
  { id: "m13", term: "@onready", definition: "Assign a var when the node is ready" },
  { id: "m14", term: "Autoload", definition: "Global singleton available everywhere" },
  { id: "m15", term: "Tween", definition: "Animate properties over time in code" },
  { id: "m16", term: "Area2D", definition: "Detect overlaps / hitboxes" },
  { id: "m17", term: "Input Map", definition: "Named actions for keys/gamepads" },
  { id: "m18", term: "instantiate()", definition: "Create an instance of a PackedScene" },
  { id: "m19", term: "_physics_process", definition: "Fixed-step update for physics/movement" },
  { id: "m20", term: "get_tree()", definition: "Access the SceneTree from a node" },
  { id: "m21", term: "clamp()", definition: "Keep a number inside min/max" },
  { id: "m22", term: "enum", definition: "Named set of constant options" },
];

export const FILL_QUESTIONS = [
  {
    id: "f1",
    template: "___ health = 100",
    answer: "var",
    options: ["var", "let", "int", "dim"],
    hint: "GDScript's keyword for variables",
  },
  {
    id: "f2",
    template: "func _ready___",
    answer: "():",
    options: ["():", "()", ":", "[]:"],
    hint: "Functions need () and a colon",
  },
  {
    id: "f3",
    template: "button.pressed.___(_on_pressed)",
    answer: "connect",
    options: ["connect", "bind", "listen", "on"],
    hint: "Godot 4 signal API",
  },
  {
    id: "f4",
    template: "health_changed.___(hp)",
    answer: "emit",
    options: ["emit", "send", "fire", "call"],
    hint: "How signals are triggered",
  },
  {
    id: "f5",
    template: "position += velocity * ___",
    answer: "delta",
    options: ["delta", "time", "fps", "speed"],
    hint: "Frame-independent motion",
  },
  {
    id: "f6",
    template: "___ Node2D",
    answer: "extends",
    options: ["extends", "inherit", "from", "super"],
    hint: "Top of almost every script",
  },
  {
    id: "f7",
    template: "___ var speed = 200",
    answer: "@export",
    options: ["@export", "@public", "@inspect", "export"],
    hint: "Inspector tweakable",
  },
  {
    id: "f8",
    template: "for i in range(3)___",
    answer: ":",
    options: [":", "{}", "do", "then"],
    hint: "Block starter",
  },
  {
    id: "f9",
    template: "await get_tree().create_timer(1.0).___",
    answer: "timeout",
    options: ["timeout", "done", "finished", "wait"],
    hint: "Timer signal name",
  },
  {
    id: "f10",
    template: "var label = ___Label",
    answer: "$",
    options: ["$", "#", "@", "&"],
    hint: "Node path shorthand",
  },
  {
    id: "f11",
    template: "if hp ___ 0:",
    answer: "==",
    options: ["==", "=", "===", ":="],
    hint: "Equality check",
  },
  {
    id: "f12",
    template: "const MAX_HP = 100  # this ___ change later",
    answer: "cannot",
    options: ["cannot", "can", "might", "should"],
    hint: "Meaning of const",
  },
  {
    id: "f13",
    template: "move_and_slide___",
    answer: "()",
    options: ["()", "(velocity)", "(delta)", "(true)"],
    hint: "Godot 4 CharacterBody2D",
  },
  {
    id: "f14",
    template: "___(\"res://icon.svg\")",
    answer: "preload",
    options: ["preload", "require", "import", "include"],
    hint: "Compile-time load",
  },
  {
    id: "f15",
    template: "node.___()",
    answer: "queue_free",
    options: ["queue_free", "destroy", "delete", "remove"],
    hint: "Safe way to remove a node",
  },
  {
    id: "f16",
    template: "@___ var sprite = $Sprite2D",
    answer: "onready",
    options: ["onready", "export", "tool", "static"],
    hint: "Assign after children exist",
  },
  {
    id: "f17",
    template: "var dir = Input.get___(\"left\",\"right\",\"up\",\"down\")",
    answer: "vector",
    options: ["vector", "axis", "dir", "stick"],
    hint: "Returns a Vector2 from actions",
  },
  {
    id: "f18",
    template: "add_to___(\"enemies\")",
    answer: "group",
    options: ["group", "team", "tag", "layer"],
    hint: "Node tagging system",
  },
  {
    id: "f19",
    template: "var e = scene.___()",
    answer: "instantiate",
    options: ["instantiate", "instance", "spawn", "new"],
    hint: "PackedScene → Node",
  },
  {
    id: "f20",
    template: "health = ___(health, 0, max_hp)",
    answer: "clamp",
    options: ["clamp", "limit", "bound", "wrap"],
    hint: "Keep inside a range",
  },
  {
    id: "f21",
    template: "func damage(amount: int) ___ void:",
    answer: "->",
    options: ["->", "=>", ":", "returns"],
    hint: "Return type arrow",
  },
  {
    id: "f22",
    template: "___ State { IDLE, RUN }",
    answer: "enum",
    options: ["enum", "const", "match", "class"],
    hint: "Named option set",
  },
  {
    id: "f23",
    template: "var t = ___()",
    answer: "create_tween",
    options: ["create_tween", "new_tween", "make_anim", "start_tween"],
    hint: "Built-in Node helper for tweens",
  },
  {
    id: "f24",
    template: "if Input.is_action_just___(\"jump\"):",
    answer: "pressed",
    options: ["pressed", "down", "tap", "hit"],
    hint: "True only on the frame it starts",
  },
];

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export const GAME_STATS = {
  bugs: BUG_QUESTIONS.length,
  matches: MATCH_PAIRS.length,
  fills: FILL_QUESTIONS.length,
};
