export const START_PATHS = [
  {
    id: "zero",
    title: "I've never written GDScript",
    short: "Brand new",
    roast: "Perfect. Zero baggage, maximum potential for glorious mistakes.",
    blurb: "Start with basics cards — variables, types, and why colon exists.",
    href: "/cards?tag=basics",
    accent: "bg-coral text-white",
    tone: "coral",
    level: "Level 1 · Foundations",
    group: "foundations",
  },
  {
    id: "some-code",
    title: "I know some programming",
    short: "Transfer",
    roast: "Cool. Now unlearn half of it — GDScript has opinions.",
    blurb: "Jump into Bug Squash and feel the Godot 4 plot twists.",
    href: "/play",
    accent: "bg-teal text-white",
    tone: "teal",
    level: "Level 1 · Practice",
    group: "foundations",
  },
  {
    id: "signals",
    title: "Signals confuse me",
    short: "Signals",
    roast: "Join the club. Membership is free; understanding costs XP.",
    blurb: "Drill signal cards, then prove it in Speed mode.",
    href: "/cards?tag=signals",
    accent: "bg-gold text-ink",
    tone: "gold",
    level: "Level 1 · Focus",
    group: "focus",
  },
  {
    id: "nodes",
    title: "Nodes & scenes feel messy",
    short: "Nodes",
    roast: "They are messy. We just teach you to mess up with style.",
    blurb: "Cards on $ paths, @onready, scenes, and instantiate().",
    href: "/cards?tag=godot",
    accent: "bg-sky text-ink",
    tone: "sky",
    level: "Level 1 · Focus",
    group: "focus",
  },
  {
    id: "movement",
    title: "I want movement & physics",
    short: "Physics",
    roast: "Delta is waiting. It has been waiting this whole time.",
    blurb: "Physics + input cards, then Fill the Blank for muscle memory.",
    href: "/cards?tag=physics",
    accent: "bg-mint text-ink",
    tone: "mint",
    level: "Level 1 · Focus",
    group: "focus",
  },
  {
    id: "speed",
    title: "Just roast me with a quiz",
    short: "Speed run",
    roast: "Say less. 60 seconds. No mercy. Maybe a little mercy.",
    blurb: "Speed mode — timed answers, sarcastic grading included.",
    href: "/cards?mode=speed",
    accent: "bg-ink text-white",
    tone: "ink",
    level: "Level 1 · Chaos",
    group: "chaos",
  },
  {
    id: "lab",
    title: "Sprite Lab (code to move)",
    short: "Sprite Lab",
    roast: "A square that walks when your Vector2 isn't lying.",
    blurb: "Interactive levels: velocity, delta, targets, hints.",
    href: "/lab",
    accent: "bg-sky text-ink",
    tone: "sky",
    level: "Hands-on · Lab",
    group: "chaos",
  },
  {
    id: "path",
    title: "Show me the full roadmap",
    short: "Roadmap",
    roast: "Integers → 3D. Yes, we documented the boring parts too.",
    blurb: "Flowchart + simplified docs from syntax to 3D games.",
    href: "/learn",
    accent: "bg-mint text-ink",
    tone: "mint",
    level: "Guide · Path",
    group: "foundations",
  },
  {
    id: "platformer",
    title: "Build a platformer",
    short: "Platformer",
    roast: "Ambition noted. Unlock after Level 1 — earn it like a boss fight.",
    blurb: "Step-by-step Godot 4 platformer tutorial (needs Level 2).",
    href: "/build/platformer",
    accent: "bg-coral text-white",
    tone: "coral",
    level: "Level 2 · Build",
    group: "boss",
    requiresLevel: 2,
  },
  {
    id: "pong",
    title: "Build ping pong vs AI",
    short: "Pong vs AI",
    roast: "You vs the computer. Spoiler: the AI doesn't get nervous.",
    blurb: "Classic paddle duel tutorial with GDScript (needs Level 2).",
    href: "/build/pong",
    accent: "bg-teal text-white",
    tone: "teal",
    level: "Level 2 · Build",
    group: "boss",
    requiresLevel: 2,
  },
];

export const PATH_GROUPS = [
  {
    id: "foundations",
    label: "Foundations",
    hint: "Brand new or transferring in",
    color: "coral",
  },
  {
    id: "focus",
    label: "Focus lanes",
    hint: "One concept, drilled hard",
    color: "gold",
  },
  {
    id: "chaos",
    label: "Hands-on chaos",
    hint: "Code, timers, no mercy",
    color: "teal",
  },
  {
    id: "boss",
    label: "Boss builds",
    hint: "Unlock at Level 2",
    color: "sky",
  },
];
