export const START_PATHS = [
  {
    id: "zero",
    title: "I've never written GDScript",
    roast: "Perfect. Zero baggage, maximum potential for glorious mistakes.",
    blurb: "Start with basics cards — variables, types, and why colon exists.",
    href: "/cards?tag=basics",
    accent: "bg-coral text-white",
    level: "Level 1 · Foundations",
  },
  {
    id: "some-code",
    title: "I know some programming",
    roast: "Cool. Now unlearn half of it — GDScript has opinions.",
    blurb: "Jump into Bug Squash and feel the Godot 4 plot twists.",
    href: "/play",
    accent: "bg-teal text-white",
    level: "Level 1 · Practice",
  },
  {
    id: "signals",
    title: "Signals confuse me",
    roast: "Join the club. Membership is free; understanding costs XP.",
    blurb: "Drill signal cards, then prove it in Speed mode.",
    href: "/cards?tag=signals",
    accent: "bg-gold text-ink",
    level: "Level 1 · Focus",
  },
  {
    id: "nodes",
    title: "Nodes & scenes feel messy",
    roast: "They are messy. We just teach you to mess up with style.",
    blurb: "Cards on $ paths, @onready, scenes, and instantiate().",
    href: "/cards?tag=godot",
    accent: "bg-sky text-ink",
    level: "Level 1 · Focus",
  },
  {
    id: "movement",
    title: "I want movement & physics",
    roast: "Delta is waiting. It has been waiting this whole time.",
    blurb: "Physics + input cards, then Fill the Blank for muscle memory.",
    href: "/cards?tag=physics",
    accent: "bg-mint text-ink",
    level: "Level 1 · Focus",
  },
  {
    id: "speed",
    title: "Just roast me with a quiz",
    roast: "Say less. 60 seconds. No mercy. Maybe a little mercy.",
    blurb: "Speed mode — timed answers, sarcastic grading included.",
    href: "/cards?mode=speed",
    accent: "bg-ink text-white",
    level: "Level 1 · Chaos",
  },
  {
    id: "lab",
    title: "Sprite Lab (code to move)",
    roast: "A square that walks when your Vector2 isn't lying.",
    blurb: "Interactive levels: velocity, delta, targets, hints.",
    href: "/lab",
    accent: "bg-sky text-ink",
    level: "Hands-on · Lab",
  },
  {
    id: "path",
    title: "Show me the full roadmap",
    roast: "Integers → 3D. Yes, we documented the boring parts too.",
    blurb: "Flowchart + simplified docs from syntax to 3D games.",
    href: "/learn",
    accent: "bg-mint text-ink",
    level: "Guide · Path",
  },
  {
    id: "platformer",
    title: "Build a platformer",
    roast: "Ambition noted. Unlock after Level 1 — earn it like a boss fight.",
    blurb: "Step-by-step Godot 4 platformer tutorial (needs Level 2).",
    href: "/build/platformer",
    accent: "bg-coral text-white",
    level: "Level 2 · Build",
    requiresLevel: 2,
  },
  {
    id: "pong",
    title: "Build ping pong vs AI",
    roast: "You vs the computer. Spoiler: the AI doesn't get nervous.",
    blurb: "Classic paddle duel tutorial with GDScript (needs Level 2).",
    href: "/build/pong",
    accent: "bg-teal text-white",
    level: "Level 2 · Build",
    requiresLevel: 2,
  },
];
